name: Project Setup
on:
  pull_request:
    types: [labeled]
    branches:    
      - master
env:
  module: utils
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    if: ${{ startsWith(gitea.event.pull_request.labels[0].name, 'Project/Release') && gitea.event.pull_request.milestone == null }}
    steps:
      - 
        name: Checkout
        uses: tiagomta/checkout@v1
        with:
          repository: vistta/vistta
          ref: ${{ gitea.event.pull_request.head.ref }}
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0
          submodules: true
      - 
        name: Version Increment
        id: version
        uses: tiagomta/npm@v1
        with:
          command: version increment "${{ gitea.event.pull_request.labels[0].name }}" --email devops@vistta.org
          working-directory: ./packages/${{ env.module }}
      - 
        name: Create Milestone
        uses: tiagomta/gitea@v1
        with:
          command: milestone create "${{ gitea.event.pull_request.labels[0].name }} (v${{ steps.version.outputs.result }})"